import fs from 'node:fs';
import assert from 'node:assert/strict';

const html=fs.readFileSync('site-src/index.html','utf8');
const live=fs.readFileSync('site-src/js/services/live-place-search.js','utf8');
const course=fs.readFileSync('site-src/js/domain/course-planner.js','utf8');
const controller=fs.readFileSync('site-src/js/controllers/app-controller.js','utf8');
const selectorCss=fs.readFileSync('site-src/selector.css','utf8');
const selector=fs.readFileSync('site-src/js/ui/quest-selector.js','utf8');
const searchController=fs.readFileSync('site-src/js/controllers/search-controller.js','utf8');
const wizard=fs.readFileSync('site-src/js/ui/wizard.js','utf8');

for(const id of ['regionLevel1','regionLevel2','regionLevel3','placeChoices','selectionSummary','regionLoadBar','regionLoadPercent','regionContinueBtn','placeLoadStatus','placeLoadBar','placeLoadPercent','rangeExpandModal','rangeExpandConfirm'])assert.ok(html.includes('id="'+id+'"'),id+' missing');
for(const removed of ['facilityChoices','map','mapStatus','courseMap','courseMapStatus','courseDetailPanel'])assert.ok(!html.includes('id="'+removed+'"'),removed+' must be removed');
assert.doesNotMatch(html,/leaflet|unpkg\.com\/leaflet/i);
assert.doesNotMatch(html,/부가조건/);
assert.doesNotMatch(html,/data-step="5"|data-step-view="5"/);
assert.match(html,/data-step="4"><b>4<\/b><span>코스/);
assert.match(wizard,/Math\.min\(4,n\)/);
assert.doesNotMatch(wizard,/main-map|facilityChoices/);
assert.doesNotMatch(searchController,/drawMap|drawCourseRoute|mapStatus|courseMapStatus/);
assert.doesNotMatch(controller,/step===5/);
assert.match(selector,/regionContinueBtn/);
assert.doesNotMatch(selector,/FACILITY_FILTERS|facilityChoices/);
assert.match(live,/curatedBeachFallback/);
assert.match(live,/해운대해수욕장/);
assert.match(live,/beach_resort/);
assert.match(course,/buildSelectedCourse|사용자 선택 장소/);
assert.match(selectorCss,/pixel-loader-frame/);
console.log('TRIP QUEST 4-step no-map selection checks passed');
